name: Deploy logstream on a VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: echo "--build-arg GITHUB_REPOSITORY=${{ github.repository }}"
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file ./build/Dockerfile --tag logstream-xc:$(date +%s) --build-arg GITHUB_REPOSITORY=${{ github.repository }}
#      - name: Launch Logstream image
#        run: docker run logstream-xc:$(date +%s)

# https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/environment-variables#default-environment-variables
